markdown:         kramdown
highlighter:      rouge
permalink:        /posts/:title/

title:            "Linux Kernel Architecture 内核笔记"
url:              http://guojing.me/linux-kernel-architecture
feed:             /linux-kernel-architecture/feed.xml
author:
    name:         GuoJing
    twitter:      twitter.com/guojing
    key:          jguoer
description:      "内核笔记"
copyright:        "CopryRight GuoJing 2012-2012 by GitHub and Jekyll"
headdesc:         "Linux Kernel Architecture 内核笔记"
headkeys:         "Linux,Kernel,Architecture,内核,笔记"
